defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: gemstone_dev
  pool: 5
  username: andersl
  password: tjenispenis12345
  host: 127.0.0.1

development:
  <<: *defaults

production:
  <<: *defaults

staging:
  <<: *defaults

test:
  <<: *defaults
  database: gemstone_test
